Добавил еще один метод просто по нику найти пользователя на github отдельно при нажатии в методе initOutgoingEvents далее binding.inputLayoutTextWindow.setStartIconOnClickListener - выходит ошибка:
ctivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call - не обработ в потоке ошибка
+ далее продолжение:
java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $